### variables
@baseUrl=http://localhost:8080/api/v1

### create a user
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "firstName": "Helen",
  "lastName": "Nguyen"
}

### submit friend request
POST {{baseUrl}}/friendships/request
Content-Type: application/json

{
  "requesterId": "2",
  "requesteeId": "4"
}

### accept friend request
POST {{baseUrl}}/friendships/accept
Content-Type: application/json

{
  "acceptorId": "4",
  "accepteeId": "2"
}

### recommend friends
POST {{baseUrl}}/friendships/recommendFriends
Content-Type: application/json

{
  "userId": "1"
}