### Variables
@baseUrl=http://localhost:8080/api/v1

### Create a user
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "firstName": "Bobby",
  "lastName": "Nguyen"
}

### Submit friend request
POST {{baseUrl}}/friendships/request
Content-Type: application/json

{
  "requesterId": "1",
  "requesteeId": "2"
}
